import { TransactionStatus } from "../../transaction/enum";
import { CoinEnum } from "../../../types/enum/coinEnum";
import { ITableColumn, ITableFilter, ITableOption } from "../model";
import { ITransactionTableData } from "./model";

export const marketTableFilters: ITableFilter[] = [
	{
		name: "Favourites",
		isActive: false,
	},
	{
		name: "Spot Markets",
		isActive: true,
	},
	{
		name: "Newly Listed",
		isActive: false,
	},
	{
		name: "All Cryptos",
		isActive: false,
	},
];

export const marketTableOptions: ITableOption[] = [
	{
		name: CoinEnum.BTC,
		isActive: true,
	},
	{
		name: CoinEnum.BNB,
		isActive: false,
	},
	{
		name: CoinEnum.ETH,
		isActive: false,
	},
	{
		name: "FIAT",
		isActive: false,
	},
	{
		name: "ALTS",
		isActive: false,
	},
];

export const depositTransactionTableColumns: ITableColumn[] = [
	{
		title: "Coin",
		dataIndex: "coin",
		key: "coin",
	},
	{
		title: "Date/Time",
		dataIndex: "date_time",
		key: "date_time",
	},
	{
		title: "Amount",
		dataIndex: "deposit_amount",
		key: "deposit_amount",
	},
	// {
	// 	title: "Destination",
	// 	dataIndex: "destination",
	// 	key: "destination",
	// },
	{
		title: "TxID",
		dataIndex: "tx_id",
		key: "tx_id",
	},
	{
		title: "Status",
		dataIndex: "status",
		key: "status",
	},
];

export const transactionTableData: ITransactionTableData[] = [
	{
		id: 1,
		coin: CoinEnum.DOGE,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 2,
		coin: CoinEnum.LTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.FAILED,
	},
	{
		id: 3,
		coin: CoinEnum.BNB,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 4,
		coin: CoinEnum.BTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 5,
		coin: CoinEnum.ETH,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 6,
		coin: CoinEnum.DOGE,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 7,
		coin: CoinEnum.LTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.FAILED,
	},
	{
		id: 8,
		coin: CoinEnum.BNB,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 9,
		coin: CoinEnum.BTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 10,
		coin: CoinEnum.ETH,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 11,
		coin: CoinEnum.DOGE,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 12,
		coin: CoinEnum.LTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.FAILED,
	},
	{
		id: 13,
		coin: CoinEnum.BNB,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 14,
		coin: CoinEnum.BTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 15,
		coin: CoinEnum.ETH,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 16,
		coin: CoinEnum.DOGE,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 17,
		coin: CoinEnum.LTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.FAILED,
	},
	{
		id: 18,
		coin: CoinEnum.BNB,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 19,
		coin: CoinEnum.BTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 20,
		coin: CoinEnum.ETH,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 21,
		coin: CoinEnum.DOGE,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 22,
		coin: CoinEnum.LTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.FAILED,
	},
	{
		id: 23,
		coin: CoinEnum.BNB,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 24,
		coin: CoinEnum.BTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 25,
		coin: CoinEnum.ETH,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 26,
		coin: CoinEnum.DOGE,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 27,
		coin: CoinEnum.LTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.FAILED,
	},
	{
		id: 28,
		coin: CoinEnum.BNB,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 29,
		coin: CoinEnum.BTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 30,
		coin: CoinEnum.ETH,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 31,
		coin: CoinEnum.DOGE,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 32,
		coin: CoinEnum.LTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.FAILED,
	},
	{
		id: 33,
		coin: CoinEnum.BNB,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 34,
		coin: CoinEnum.BTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 35,
		coin: CoinEnum.ETH,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 36,
		coin: CoinEnum.DOGE,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 37,
		coin: CoinEnum.LTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.FAILED,
	},
	{
		id: 38,
		coin: CoinEnum.BNB,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 39,
		coin: CoinEnum.BTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 40,
		coin: CoinEnum.ETH,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 41,
		coin: CoinEnum.DOGE,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 42,
		coin: CoinEnum.LTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.FAILED,
	},
	{
		id: 43,
		coin: CoinEnum.BNB,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 44,
		coin: CoinEnum.BTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 45,
		coin: CoinEnum.ETH,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 46,
		coin: CoinEnum.DOGE,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 47,
		coin: CoinEnum.LTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.FAILED,
	},
	{
		id: 48,
		coin: CoinEnum.BNB,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 49,
		coin: CoinEnum.BTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 50,
		coin: CoinEnum.ETH,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 51,
		coin: CoinEnum.DOGE,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 52,
		coin: CoinEnum.LTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.FAILED,
	},
	{
		id: 53,
		coin: CoinEnum.BNB,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 54,
		coin: CoinEnum.BTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 55,
		coin: CoinEnum.ETH,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 56,
		coin: CoinEnum.DOGE,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 57,
		coin: CoinEnum.LTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.FAILED,
	},
	{
		id: 58,
		coin: CoinEnum.BNB,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
	{
		id: 59,
		coin: CoinEnum.BTC,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.SUCCESSFUL,
	},
	{
		id: 60,
		coin: CoinEnum.ETH,
		date_time: new Date().toISOString(),
		deposit_amount: 23.123456,
		destination: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		tx_id: "1AnimEmYAmQdZdz9xQ7dE7wLrEoCHTVQkL",
		status: TransactionStatus.PENDING,
	},
];

export const depositHistoryDummy: any[] = [
	{
		address: "14YCEfxterp5uJ3Njc62sh3qbmVPUKdN4H",
		addressTag: "",
		amount: "0.00023972",
		coin: "DOGE",
		confirmTimes: "1/1",
		insertTime: 1642634686001,
		network: "DOGE",
		status: 1,
		transferType: 0,
		txId: "ad01ed32697a26a8a6f450e719d11ca5ca241cc2f68a1dc8140e07b8e127950d",
		unlockConfirm: 2,
		walletType: 0,
	},
	{
		address: "14YCEfxterp5uJ3Njc62sh3qbmVPUKdN4H",
		addressTag: "",
		amount: "0.00023972",
		coin: "LTC",
		confirmTimes: "1/1",
		insertTime: 1642634686002,
		network: "LTC",
		status: 2,
		transferType: 0,
		txId: "ad01ed32697a26a8a6f450e719d11ca5ca241cc2f68a1dc8140e07b8e127950d",
		unlockConfirm: 2,
		walletType: 0,
	},
	{
		address: "14YCEfxterp5uJ3Njc62sh3qbmVPUKdN4H",
		addressTag: "",
		amount: "0.00023972",
		coin: "ETH",
		confirmTimes: "1/1",
		insertTime: 1642634686003,
		network: "ETH",
		status: 0,
		transferType: 0,
		txId: "ad01ed32697a26a8a6f450e719d11ca5ca241cc2f68a1dc8140e07b8e127950d",
		unlockConfirm: 2,
		walletType: 0,
	},
];
